<form id="img_form" method="post" accept-charset="utf-8" enctype="multipart/form-data">
  <p>
    <label for="name">Namn</label>
    <input type="text" name="name" value="" id="name" />
  </p>
  <p>
    <label for="image">Bild</label>
    <input type="file" name="image" id="image"/>
  </p>
  <p>
    <label for="description">Beskrivning</label>
    <textarea name="description" id="description" rows="8" cols="40"></textarea>
  </p>
  <p><input type="submit" value="Ladda upp &rarr;"></p>
</form>